### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by ldiex** [luogu-dev/cyaron#1]
Do you tell me how to use this function? 
**I am confused !**

**Comment by lin714093880** [comment]
Documentations will be ready very soon.
Meanwhile please read test.py and cyaron/*.py and figure out yourself, or please patiently wait for our documentation. Contributions are also welcome of course.

**Comment by DistEx** [comment]
Ah~ I know.
还是用中文吧……

**Comment by lin714093880** [comment]
反正晚上下课了我加文档咯
弄好了就close掉这个

**Comment by mrj1018** [comment]
其实我觉得我可以帮写一写文档……
我fork一份写吧~

**Comment by lin714093880** [comment]
好啊，麻烦新建一个docs文件夹往里面塞

**Comment by mrj1018** [comment]
@lin714093880 Python 库内的文档注释好了，但是Markdown文档还没好。现在弄好的就是这三份代码。
文档注释格式、英语语法之类的并不熟悉，请见谅，希望能对这个项目有些许的帮助！
明天有时间就写一写MD文档。MD主要就是把__docs__里面的一些东西用中文表述吧，再加一些示例。
https://github.com/mrj1018/cyaron/blob/master/cyaron/__init__.py
https://github.com/mrj1018/cyaron/blob/master/cyaron/graph.py
https://github.com/mrj1018/cyaron/blob/master/cyaron/io.py

**Comment by lin714093880** [comment]
感谢啊。弄好了麻烦PR过来

**Comment by fjzzq2002** [comment]
@mrj1018
QAQ看了看注释感觉有点问题？
tree函数注释有误，参数可以为小数，表示百分比
weight_gen在部分函数中没有注释（大概还没写完？），并且不一定要返回weight_limit范围内的权，也不一定要是数

**Comment by lin714093880** [comment]
@fjzzq2002 @mrj1018 
我下午用手机的没认真看
@mrj1018 您PR的时候我会再注意审核一下

**Comment by lin714093880** [comment]
@mrj1018 docs如果用Wiki来搞会不会更好一些？我在想这个问题……

**Comment by mrj1018** [comment]
@fjzzq2002 请问您“tree函数注释有误，参数可以为小数，表示百分比”指的是chain和flower吗？谢谢
其他是因为更新这个的时候没有更完，感谢指正！
(然而这是我在PR以后才改的……PR用的是最新版本吗？)

**Comment by mrj1018** [comment]
@lin714093880 确实，我其实不知道MD文档怎么搞。而且确实有不少项目就是用的Wiki(如果是这样我可能更熟悉Wiki)

**Comment by lin714093880** [comment]
@mrj1018 我说的是github自带那个wiki里面也是md的，fork过去直接改然后一样pr就可以
然后 可能你的那边确实已经不是上游最新的了…昨天大概经历了30+ commit 版本号都刷了五个

**Comment by lin714093880** [comment]
文档已经填完，close。
