### ISSUE TITLE
要加的新功能：对拍器/数学库

### ISSUE THREAD

**Issue by kkksc03** [luogu-dev/cyaron#12]
对拍器就是生成数据，然后两个可执行文件，给出输出，比较。
比较的话，可以用linux的diff，也能用win的fc，不过还是用洛谷评测机那一套搬运过来。
数学库啊，从那个pas的搬过来啊

**Comment by lin714093880** [comment]
数学库可能可以用一部分numpy的轮子，或者提供更适合OI使用的封装。

**Comment by lin714093880** [comment]
对拍器已加
