### ISSUE TITLE
貌似是一个 bug？

### ISSUE THREAD

**Issue by figurexyang** [luogu-dev/cyaron#123]
vector.py 文件内56-57行：
        if mode == VectorRandomMode.repeatable:
            result = [[random.randint(x, y) for x, y in zip(offset, length)] for _ in range(num)]
        elif mode == VectorRandomMode.float:
            result = [[random.uniform(x, y) for x, y in zip(offset, length)] for _ in range(num)]
这里是否有问题？random.randint(x,y)与random.uniform(x, y)的返回的值范围是[x,y],而offset, length对应的是左端点和长度。应该改为:
result = [[random.randint(x, x+y) for x, y in zip(offset, length)] for _ in range(num)]
result = [[random.uniform(x, x+y) for x, y in zip(offset, length)] for _ in range(num)]

这个bug可以通过下面这个样例发现：
Vector.random(100,[(7,8)],vector.VectorRandomMode.repeatable)

**Comment by houmy555809** [comment]
你直接发布 pull requests 吧
