### ISSUE TITLE
Vector.random()使用大量内存

### ISSUE THREAD

**Issue by LiuZiaoPeter** [luogu-dev/cyaron#139]
调用`Vector.random(10**5, ([1, 10**9]))`会弹出`MemoryError`，但是使用如下代码生成的列表可以保证时空复杂度：
```python
def randlist(l, lim):  # time complexity: O(l)
    ret = []
    for i in range(l):
        ret.append(randint(lim[0], lim[1]))
    return ret


def rand_norep_list(l, lim):  # expected time complexity: O(l log l)
    ret = []
    for i in range(l):
        nxt = randint(lim[0], lim[1])
        while nxt in ret:
            nxt = randint(lim[0], lim[1])
        ret.append(nxt)
```

**Comment by weilycoder** [comment]
这边没法复现，能提供报错的代码吗？

**Comment by weilycoder** [comment]
而且 `Vector.random(10**5, ([1, 10**9]))` 和你的代码的效果显然不同

**Comment by Mr-Python-in-China** [comment]
> 而且 `Vector.random(10**5, ([1, 10**9]))` 和你的代码的效果显然不同
> 
> 并且谁告诉你查某个元素是否在列表里是 $O(1)$ 的？
> 
> 你代码在生成数据接近样本空间时的期望复杂度是 $O(n^2 \log n)$ 的（Python 3.8）。

你急啥，套个set不就对了

**Comment by LiuZiaoPeter** [comment]
> 这边没法复现，能提供报错的代码吗？
> 
> 顺便请提供版本

3.12.7，机带RAM32GB

**Comment by weilycoder** [comment]
问题是我没法复现

```python
from random import *
from cyaron.vector import *


def cost(func, *args, **kwargs):
    import time, tracemalloc

    st = time.time()
    tracemalloc.start()
    func(*args, **kwargs)
    peak_mem = tracemalloc.get_traced_memory()[1]
    tracemalloc.stop()
    used_time = time.time() - st
    return peak_mem / 1024 / 1024, used_time

print(cost(Vector.random, *(10**5, ([1, 10**9]))))
# (18.875548362731934, 0.7309601306915283)
```

**Comment by LiuZiaoPeter** [comment]
> 而且 `Vector.random(10**5, ([1, 10**9]))` 和你的代码的效果显然不同
> 
> 并且谁告诉你查某个元素是否在列表里是 O ( 1 ) 的？
> 
> 你代码在生成数据接近样本空间时的期望复杂度是 O ( n 2 log ⁡ n ) 的（Python 3.8）。

把他改成效果一样的也就加个 $O(n)$

**Comment by LiuZiaoPeter** [comment]
> 问题是我没法复现
> 
> ```python
> from random import *
> from cyaron.vector import *
> 
> 
> def cost(func, *args, **kwargs):
>     import time, tracemalloc
> 
>     st = time.time()
>     tracemalloc.start()
>     func(*args, **kwargs)
>     peak_mem = tracemalloc.get_traced_memory()[1]
>     tracemalloc.stop()
>     used_time = time.time() - st
>     return peak_mem / 1024 / 1024, used_time
> 
> print(cost(Vector.random, *(10**5, ([1, 10**9]))))
> # (18.875548362731934, 0.7309601306915283)
> ```

要不你直接print或者存在一个变量里试试

**Comment by weilycoder** [comment]
区别不大

```python
import sys

from random import *
from cyaron.vector import *

sys.stdout = open("log.txt", "w", encoding="utf-8")

def cost(func, *args, **kwargs):
    import time, tracemalloc

    st = time.time()
    tracemalloc.start()
    print(func(*args, **kwargs))
    peak_mem = tracemalloc.get_traced_memory()[1]
    tracemalloc.stop()
    used_time = time.time() - st
    return peak_mem / 1024 / 1024, used_time

print(cost(Vector.random, *(10**5, ([1, 10**9]))), file=sys.stderr)
# (19.435447692871094, 1.7963850498199463)
```

顺便，这一版我用 Py312 跑的，上一版是 Py38

**Comment by weilycoder** [comment]
> > 而且 `Vector.random(10**5, ([1, 10**9]))` 和你的代码的效果显然不同
> > 并且谁告诉你查某个元素是否在列表里是 
> >   O
> >   (
> >   1
> >   )
> >  的？
> > 你代码在生成数据接近样本空间时的期望复杂度是 
> >   O
> >   (
> >   
> >     n
> >     2
> >   
> >   log
> >   ⁡
> >   n
> >   )
> >  的（Python 3.8）。
> 
> 你急啥，套个set不就对了

确实，不过语义不一样，他自己的是生成 1e5 个数，调的函数是生成 1e5 个二维向量，不过应该是调的函数参数传错了

**Comment by LiuZiaoPeter** [comment]
> Vector.random(10**5, ([1, 10**9]))

你可以直接：

```python
from cyaron import *

vr = Vector.random(10**5, ([1, 10**9]))
print(vr)
```

**Comment by LiuZiaoPeter** [comment]
如果还是不行的话可以把9改成18

**Comment by weilycoder** [comment]
@LiuZiaoPeter 更新到cyaron最新版仍然报错吗？复现不了，监测峰值内存是 20M 左右。

**Comment by LiuZiaoPeter** [comment]
> @LiuZiaoPeter 更新到cyaron最新版仍然报错吗？复现不了，监测峰值内存是 20M 左右。
> 
> 或者说你 cyaron 啥版本？

原来是0.5.0，更新至0.6.0之后没这个问题了。

抱歉浪费你的时间。

**Comment by weilycoder** [comment]
没事，但是 0.6.0 没修 Vector 啊？

我还是很好奇具体啥原因的

**Comment by Mr-Python-in-China** [comment]
上个版本已经修过了

**Comment by Mr-Python-in-China** [comment]
> 没事，但是 0.6.0 没修 Vector 啊？
> 
> 我还是很好奇具体啥原因的

你看我提交记录不就知道问题在哪了吗

**Comment by weilycoder** [comment]
看见了，枚举类导致的。。。

为啥 Vector 出这么多锅？
