### ISSUE TITLE
math.py 的筛质数有问题

### ISSUE THREAD

**Issue by Yon-da** [luogu-dev/cyaron#22]
prime_sieve(25)
[2, 3, 5, 9, 11, 15, 17, 23]

prime_sieve(20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\cyaron\math.py", line 258, in prime_sieve
    sieve[i*int(i/2)::i] = [False] * (int((n-i*i-1)/(2*i))+1)
ValueError: attempt to assign sequence of size 2 to extended slice of size 3

**Comment by FangZizheng** [comment]
+1

**Comment by FangZizheng** [comment]
def p(n):
    k = n//2
    sieve = [True] * k
    for i in xrange(3,int(n**0.5)+1,2):
        if sieve[i//2]:
            sieve[i*i//2::i] = [False] * ((n-i*i-1)//(2*i)+1)
    return [2] + [2*i+1 for i in range(1,k) if sieve[i]]

**Comment by MrMorning** [comment]
#30
Is it solved?
