### ISSUE TITLE
生成最后一个数据的答案时有概率生成空文件

### ISSUE THREAD

**Issue by outloudvi** [luogu-dev/cyaron#24]
环境: Windows 10 + Python 3.6.2 + IDLE
在 IDLE 中 `Run Module` 后生成最后的一组数据有概率是空文件，此时立即尝试在 cmd 中运行程序写入后有可能出现 `另一个程序正在使用此文件，进程无法访问。` 的错误。

**Comment by lin714093880** [comment]
Known issue
因为这种时候上最后一个IO没有被关闭，缓存没写入，可以用with IO()....解决
