### ISSUE TITLE
对拍器无法正常使用

### ISSUE THREAD

**Issue by wwzzkk** [luogu-dev/cyaron#32]
环境：win7+py3
执行：`Compare.program("a.exe", "b.exe", input=input_io,std_program="std.exe",stop_on_incorrect=True)`
报错：`TypeError: program() got an unexpected keyword argument 'stop_on_incorrect'`
翻了一下commits记录，大概是对company.py进行了一些修改，对于传入的stop_on_incorrect参数进行调整，经检测，使用较早的版本中的company.py替换后可以正常使用。
//python不太会，只能提个issue啦;-)

**Comment by lin714093880** [comment]
由于现在使用了多线程比较器，这个参数已经不再使用（且也无法实现）。
为保证向后兼容稍后放出更新（但是唯一的作用就是接受此参数并给 warning ），稍后修正文档
