### ISSUE TITLE
为什么输入没有换行

### ISSUE THREAD

**Issue by ciao1** [luogu-dev/cyaron#59]
from cyaron import * 
n=5
for i in range(1,7):
	test_data=IO(file_prefix="test", data_id=i)
	str1=String.random(5,charset="100")
	test_data.input_writeln(str1)
	test_data.output_gen("e:\\NOIP\\maze2\\maze_lujin.exe")

输入文件中没有换行

**Comment by moesoha** [comment]
@ciao1 早期版本的 Windows 记事本不会显示只有 \n 的换行

**Comment by ciao1** [comment]
@moesoha 所以空格也不会显示？但不影响测试结果？

**Comment by moesoha** [comment]
@ciao1 你可以使用 Notepad++ 等软件打开就会发现是有的
绝大部分评测工具不会被影响
