### ISSUE TITLE
关于可以添加的新功能

### ISSUE THREAD

**Issue by WAAutoMaton** [luogu-dev/cyaron#6]
有dalao来列一下吗？一下子没有想到什么。

**Comment by lin714093880** [comment]
oeis
向量
字符串

**Comment by mrj1018** [comment]
有个地方我觉得可能不是那么好看，比如说class IO里面input的方法没有前缀，output的方法却有前缀，虽然这是因为input的这些方法比较常用，但是，是不是有点“钦定”input的感觉？

**Comment by lin714093880** [comment]
@mrj1018 
是啊，因为谁没事写output，一般都是调用一个标程来跑

**Comment by lin714093880** [comment]
当然有点钦定，因为之前有一个api的设计的原因，不过现在这个设计废除了，倒是加个前缀也没事

**Comment by lin714093880** [comment]
看了一下啊，oeis不适合加进来，一个是网络请求的问题，再来是这个东西感觉没太大做成库的必要，真的要用自己import一下别人的库然后配合IO库用很容易的

**Comment by fjzzq2002** [comment]
生成简单多边形、凸包...

**Comment by lin714093880** [comment]
这个我太弱了不会写啊，zzq有什么想法吗

**Comment by fjzzq2002** [comment]
凸包简单，简单多边形我正在看资料...有毒

**Comment by kkksc03** [comment]
预设几组数据范围的数组

**Comment by fjzzq2002** [comment]
这个简单多边形的生成在共线点比较多的时候理论上有一定概率gg...建议使用实数点对生成。
