### ISSUE TITLE
希望有图的一些简单算法帮助输出更丰富的数据

### ISSUE THREAD

**Issue by christopher-woo** [luogu-dev/cyaron#69]
如最短路及最短路的节点个数，lca等

**Comment by william-song-shy** [comment]
~~无法理解的描述~~

**Comment by Wallbreaker5th** [comment]
没有必要吧。这些算法应该交给 std 去实现，而非 generator。

**Comment by william-song-shy** [comment]
是啊


---原始邮件---
发件人: &quot;洪文杰&quot;<notifications@github.com&gt;
发送时间: 2019年10月6日(星期日) 中午11:54
收件人: &quot;luogu-dev/cyaron&quot;<cyaron@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;william-song-shy&quot;<2560814258@qq.com&gt;;
主题: Re: [luogu-dev/cyaron] 希望有图的一些简单算法帮助输出更丰富的数据 (#69)



没有必要吧。这些算法应该交给 std 去实现，而非 generator。
 
&mdash;
