### ISSUE TITLE
在 Arch Linux 的 AUR 上打了包

### ISSUE THREAD

**Issue by ayalhw** [luogu-dev/cyaron#77]
在 Arch Linux 的 AUR 上打了包，方便在 ArchLinux 上的安装
AUR 中的地址 https://aur.archlinux.org/packages/python-cyaron/

**Comment by william-song-shy** [comment]
建议在描述中加入关于洛谷的版权说明

**Comment by ayalhw** [comment]
> 建议在描述中加入关于洛谷的版权说明

ok
