### ISSUE TITLE
vector.py中文注释没加#coding=utf-8

### ISSUE THREAD

**Issue by fjzzq2002** [luogu-dev/cyaron#8]
Rt. 部分版本的python会报错

**Comment by lin714093880** [comment]
其实我都觉得代码里应该就不要有非ascii字符，防止奇怪的python23问题…

**Comment by DistEx** [comment]
唔不用py2不就行了吗……

**Comment by lin714093880** [comment]
高举Python2大旗的我突然有点想**（滑稽

**Comment by mrj1018** [comment]
我还是确实觉得代码里的注释可能英文更好，Wiki或者MD注释再用中文(况且这里是Github,最好再搞个英文版)。
Py 2/3 方面，毕竟Guido都已经屡次推荐切换到Py 3了，所以我觉得可能Py 3更面向未来……

**Comment by lin714093880** [comment]
这不代表可以不资兹py2啊
