### ISSUE TITLE
math库需要修改

### ISSUE THREAD

**Issue by wongdark2017** [luogu-dev/cyaron#84]
`fractions`的`gcd`函数已经变为`math`的`gcd`函数了。望做一下区分。

**Comment by gkkeys** [comment]
铜球

**Comment by G-MCCF** [comment]
同求。

**Comment by kkksc03** [comment]
fixed in <https://github.com/luogu-dev/cyaron/commit/d27caf0b371f93c498a6cc8caa458113e1fe0037>
