### ISSUE TITLE
关于非联通图的生成

### ISSUE THREAD

**Issue by MAL-iu** [luogu-dev/cyaron#85]
怎么样能生成一个非联通的有向无环图呢，貌似graph里没有loop这个参数。

**Comment by kkksc03** [comment]
you can use `graph = Graph.DAG(n, m)` to generate one directed acyclic graph. If you have to make a 'Non-connected graph', you can generate multiple DAGs and change the number of the vertices.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luogu-dev/cyaron"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 晚上7:11
收件人:&nbsp;"luogu-dev/cyaron"<cyaron@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[luogu-dev/cyaron] 关于非联通图的生成 (#85)





 
怎么样能生成一个非联通的有向无环图呢，貌似graph里没有loop这个参数。
