### ISSUE TITLE
希望能在贡献者名单里加上各位作者的原名，便于cite

### ISSUE THREAD

**Issue by iphelf** [luogu-dev/cyaron#88]
做实验生成数据的时候用这个挺舒服的，想加到references里，需要作者姓名:
>  C. Wang, T. Lin, Z. Zhong, and R. Meng, “Cyaron: Yet another random olympic-informatics test data generator,” https://github.com/luogu-dev/cyaron, 2021.

前面4个id都能Google到名字，最后两个实在搜不到：@wyr123 @shyakocat，方便透露一下姓名不？拼音就行

**Comment by kkksc03** [comment]
wyr123 是 Wang Yanrong  

但shyakocat 还真不认识。

**Comment by iphelf** [comment]
好嘞，谢谢

**Comment by iphelf** [comment]
shyakocat的已经问到了。
