### ISSUE TITLE
cyaron能生成Python程序的数据吗

### ISSUE THREAD

**Issue by ciao1** [luogu-dev/cyaron#89]
如题，看介绍是对exe文件进行数据生成，能否为.py程序生成数据？

**Comment by kkksc03** [comment]
Yes, as long as you run a command using standard input/output.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;IWantYou&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月9日(星期二) 下午2:49
收件人:&nbsp;&quot;luogu-dev/cyaron&quot;<cyaron@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[luogu-dev/cyaron] cyaron能生成Python程序的数据吗 (#89)

**Comment by ciao1** [comment]
为什么我运行后out文件中没有结果
from cyaron import *
for i in range(1,6):
	test_data=IO(file_prefix="ab",data_id=i)
	a=randint(1,100)
	b=randint(1,100)
	test_data.input_writeln(a)
	test_data.input_writeln(b)
	test_data.output_gen("D:\\ab.py")

**Comment by thallium** [comment]
因为python文件不能直接运行

**Comment by ciao1** [comment]
看来还是需要exe才能生成。应该是不支持解释性语言

**Comment by lin714093880** [comment]
可以，不是那么运行的

**Comment by ciao1** [comment]
> 可以，不是那么运行的

那如何运行呢？

**Comment by weilycoder** [comment]
`test_data.output_gen("python D:\ab.py")`
