### ISSUE TITLE
Python3.9 `gcd` no longer in module `fractions`

### ISSUE THREAD

**Issue by Ahacad** [luogu-dev/cyaron#90]
`ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)`

[official document here](https://docs.python.org/3/library/fractions.html): `Changed in version 3.9: The math.gcd() function is now used to normalize the numerator and denominator. math.gcd() always return a int type. Previously, the GCD type depended on numerator and denominator.`

**Comment by william-song-shy** [comment]
It has been fixed in #84  .

**Comment by Ahacad** [comment]
OK, then it should be the version problem. Pypi still only has the [`cyaron v0.4.2`](https://pypi.org/project/cyaron/), and the last GitHub release was in 2019, will another release be considered?

**Comment by william-song-shy** [comment]
You could remind the manager to release a new version

**Comment by Ahacad** [comment]
I'm not sure who to go to, maybe @lin714093880 could you make a new release?

**Comment by lin714093880** [comment]
Published 0.4.3
